/**
 * Authentication and Cookie Utilities
 * Mirrors the Playwright qa-automation pattern
 * 
 * Cookies are generated by utils/cookies-setup.js and loaded from cookies.json
 */

import { open } from 'k6';

// Load ALL cookies from JSON file (generated by cookies-setup.js)
// This mirrors the Playwright pattern: generate cookies once, reuse in all tests
let allCookies = [];

try {
  const cookiesData = open('../utils/cookies.json');
  allCookies = JSON.parse(cookiesData);
  console.log(`✅ Loaded ${allCookies.length} cookies from cookies.json`);
} catch (error) {
  console.warn('⚠️  cookies.json not found. Run "npm run cookies-setup" first.');
  console.warn('   Tests will run without authentication cookies.');
}

/**
 * Get all authentication cookies from cookies.json
 * Returns all cookies as-is - no filtering, no transformation
 */
export function getAuthCookies() {
  return allCookies;
}

/**
 * Setup authenticated browser context with cookies
 * @param {Browser} browser - k6 browser instance
 * @returns {Promise<BrowserContext>} - Authenticated browser context
 */
export async function setupAuthenticatedContext(browser) {
  const context = await browser.newContext();
  const cookies = getAuthCookies();
  
  // Add all cookies from cookies.json
  if (cookies.length > 0) {
    await context.addCookies(cookies);
    console.log(`✅ Added ${cookies.length} cookies to browser context`);
  }
  
  return context;
}

/**
 * Check if authentication cookies are loaded
 * @returns {boolean}
 */
export function hasAuthCookies() {
  return allCookies.length > 0;
}
